
import javax.sql.rowset.JdbcRowSet;
import javax.swing.JButton;
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sasiroot
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHoli = new javax.swing.JButton();
        btnOkki = new javax.swing.JButton();
        btnPls = new javax.swing.JButton();
        btnPls1 = new javax.swing.JButton();
        btnPls2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        btnHoli.setText("Holi");
        btnHoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDialog(evt);
            }
        });
        getContentPane().add(btnHoli);

        btnOkki.setText("Okki");
        btnOkki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDialog(evt);
            }
        });
        getContentPane().add(btnOkki);

        btnPls.setText("Pls");
        getContentPane().add(btnPls);

        btnPls1.setText("Pls");
        getContentPane().add(btnPls1);

        btnPls2.setText("Pls");
        getContentPane().add(btnPls2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDialog
        // TODO add your handling code here:
        
        Dialog dialog = new Dialog(MainFrame.this, true);
        JButton btn = (JButton)evt.getSource();
        dialog.setLbl1(btn.getText());
        dialog.setVisible(true);
        
    }//GEN-LAST:event_openDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoli;
    private javax.swing.JButton btnOkki;
    private javax.swing.JButton btnPls;
    private javax.swing.JButton btnPls1;
    private javax.swing.JButton btnPls2;
    // End of variables declaration//GEN-END:variables
}
